### ISSUE TITLE
Speed Mode lock

### ISSUE THREAD

**Issue by Raulfin** [Drahsid/FFXIITZA-FPS-Unlocker#35]
After launching ff12za and fpsu if you click inside the console window, that shows what fpsu is doing, the game speed will become locked to whatever it is currently at, requiring a game restart to correct.

**Comment by Raulfin** [comment]
Pressing the buttons to change the speed mode will show the changes to the arrows as expected, but the game will continure to run at the speed it was at when the console was clicked in.
Clicking on the top bar to move/minimize the console will not affect it, only clicking in the text area.

**Comment by Drahsid** [comment]
This is an issue with conhost and the command prompt, it has nothing to do with the hook. You can unfreeze by deselecting in the command prompt window. This can be done by pressing return while it is in focus or disabling the feature in the command prompt's properties. 
The console freezes the thread it is processed in since the console comes from the main thread of the game, what you described is the expected result.
